# Generated by Django 5.1.15 on 2026-09-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCEEDED', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('SERVICE_KEY_CREATED', 'Service key created'), ('SERVICE_KEY_ROTATED', 'Service key rotated'), ('SERVICE_KEY_REVOKED', 'Service key revoked')], max_length=32),
        ),
    ]
