# Generated by Django 5.1.15 on 2026-09-09 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='service_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('service_id',), name='unique_current_key_per_service'),
        ),
    ]
