"""add health check fields

Revision ID: 2d67694099f1
Revises: bde1c4eecb99
Create Date: 2026-09-02 20:50:13.251973

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2d67694099f1'
down_revision: str | Sequence[str] | None = 'bde1c4eecb99'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'last_checked_at')
    op.drop_column('services', 'latency_ms')
    # ### end Alembic commands ###
