"""add simulation_url to services

Revision ID: 89fae3221ad5
Revises: fcd807ea7c6d
Create Date: 2026-09-09 15:46:36.211143

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '89fae3221ad5'
down_revision: str | Sequence[str] | None = 'fcd807ea7c6d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('simulation_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'simulation_url')
    # ### end Alembic commands ###
