"""add auth_token to services

Revision ID: fcd807ea7c6d
Revises: 2d67694099f1
Create Date: 2026-09-08 21:23:16.537088

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'fcd807ea7c6d'
down_revision: str | Sequence[str] | None = '2d67694099f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('auth_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'auth_token')
    # ### end Alembic commands ###
