"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Repo root, resolved from this file rather than the working directory — mirrors
# services/fastapi_registry/config.py so both services find the same .env regardless
# of whether they're invoked via manage.py, gunicorn, or pytest.
REPO_ROOT = BASE_DIR.parent.parent
load_dotenv(REPO_ROOT / ".env")


# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to a fixed non-secret value when unset: DJANGO_SETTINGS_MODULE is a
# session-wide pytest-django option (pyproject.toml), so importing these settings
# happens for the *entire* test session, including fastapi_registry's suite, before
# any test runs. A clean checkout with no .env (CI, a fresh worktree) would otherwise
# hit a bare KeyError at collection time and take every test down with it.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "insecure-test-key-do-not-use-in-prod")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

# Comma-separated in .env, e.g. "devpulse.example.com,localhost". Empty is fine for
# local dev (DEBUG=True auto-allows localhost/127.0.0.1), but manage.py check --deploy
# warns (W020) and gunicorn with DEBUG=False will 400 everything until this is set.
ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
]

# AUTH_USER_MODEL intentionally not set: the `accounts` app (custom user + RBAC) hasn't
# landed yet. Do not run `manage.py migrate` before it does — that creates auth_user
# under the default model, and switching AUTH_USER_MODEL afterwards means dropping and
# recreating core_db rather than a normal migration.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Non-secret local defaults below (matching compose.yaml / .env.example) so importing
# this module never raises KeyError without a .env — see the SECRET_KEY comment above.
# A test run without a real Postgres reachable at these coordinates still fails, just
# as an isolated DB-test failure rather than crashing collection for every test.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get("CORE_DB_NAME", "core_db"),
        'USER': os.environ.get("DJANGO_DB_USER", "django_user"),
        'PASSWORD': os.environ.get("DJANGO_DB_PASSWORD", "insecure-test-password"),
        'HOST': os.environ.get("POSTGRES_HOST", "localhost"),
        'PORT': os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
